data_paths:
  label_data: "project/resources/challenge_data.csv"
  reader_history: "project/resources/challenge_reader_history.csv"
  page_embeddings: "project/resources/challenge_page_embeddings.csv"

model_params:
  max_len: 150
  embedding_dim: 256
  learning_rate: 0.001

training_params:
  batch_size: 32
  epochs: 50